import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync, mkdirSync } from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const outdir = prod ? "dist" : ".";
const pluginDir = "exampleVault/.obsidian/plugins/bases-charts";
const filesToCopy = ["main.js", "manifest.json", "styles.css"];

const copyToVaultPlugin = {
	name: "copy-to-vault",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			mkdirSync(pluginDir, { recursive: true });
			for (const file of filesToCopy) {
				try {
					copyFileSync(file, `${pluginDir}/${file}`);
				} catch (e) {
					console.warn(`Failed to copy ${file}:`, e.message);
				}
			}
			console.log(`Copied to ${pluginDir}`);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outdir}/main.js`,
	minify: prod,
	plugins: prod ? [] : [copyToVaultPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
